
package by.training.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import by.training.service.domain.Expression;
import by.training.service.domain.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SOAPService", targetNamespace = "http://service.training.by/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SOAPService {


    /**
     * 
     * @param expression
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getResult", targetNamespace = "http://service.training.by/", className = "by.training.service.domain.GetResult")
    @ResponseWrapper(localName = "getResultResponse", targetNamespace = "http://service.training.by/", className = "by.training.service.domain.GetResultResponse")
    @Action(input = "http://service.training.by/SOAPService/getResultRequest", output = "http://service.training.by/SOAPService/getResultResponse")
    public double getResult(
        @WebParam(name = "expression", targetNamespace = "")
        Expression expression);

}
